destination: ./_site
auto: true
lsi: false
server_port: 4000
markdown: rdiscount
pygments: true
permalink:   /article/:title.html
url: http://www.maheshsubramaniya.com
site_name: Mahesh Subramaniya
sub_title: engineer, developer, photographer, coffee lover
site_description: Experiences of sofware development
author: Mahesh Subramaniya
google_robots: noodp, noydir
tags: J2EE, J2EE Frameworks, Enterprise Architecture, Distributed, Cloud Computing, Performance
paginate: 10
twitter_id: mymindleaks
excerpt_separator: ""
url_photo: http://500px.com/maheshsubramaniya
url_food: food.html
url_tamil: tamil.html

maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
